const TRAIN_STATIONS_DATA = [
  {
    LocationCode: "AC",
    PublicStopId: "1AC",
    LocationName: "Acton GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "AD",
    PublicStopId: "1AD",
    LocationName: "Allandale Waterfront GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "AG",
    PublicStopId: "1AG",
    LocationName: "Agincourt GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "AJ",
    PublicStopId: "1AJ",
    LocationName: "Ajax GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "AL",
    PublicStopId: "1AL",
    LocationName: "Aldershot GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "AP",
    PublicStopId: "1AP",
    LocationName: "Appleby GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "AU",
    PublicStopId: "1AU",
    LocationName: "Aurora GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "BA",
    PublicStopId: "1BA",
    LocationName: "Barrie South GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "BD",
    PublicStopId: "1BD",
    LocationName: "Bradford GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "BE",
    PublicStopId: "1BE",
    LocationName: "Bramalea GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "BL",
    PublicStopId: "1BL",
    LocationName: "Bloor GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "BM",
    PublicStopId: "1BM",
    LocationName: "Bloomington GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "BO",
    PublicStopId: "1BO",
    LocationName: "Bronte GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "BR",
    PublicStopId: "1BR",
    LocationName: "Brampton Innovation District GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "BU",
    PublicStopId: "1BU",
    LocationName: "Burlington GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "CE",
    PublicStopId: "1CE",
    LocationName: "Centennial GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "CL",
    PublicStopId: "1CL",
    LocationName: "Clarkson GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "CO",
    PublicStopId: "1CO",
    LocationName: "Cooksville GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "DA",
    PublicStopId: "1DA",
    LocationName: "Danforth GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "DI",
    PublicStopId: "1DI",
    LocationName: "Dixie GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "DW",
    PublicStopId: "1DW",
    LocationName: "Downsview Park GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "EA",
    PublicStopId: "1EA",
    LocationName: "East Gwillimbury GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "EG",
    PublicStopId: "1EG",
    LocationName: "Eglinton GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "ER",
    PublicStopId: "1ER",
    LocationName: "Erindale GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "ET",
    PublicStopId: "1ET",
    LocationName: "Etobicoke North GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "EX",
    PublicStopId: "1EX",
    LocationName: "Exhibition GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "GE",
    PublicStopId: "1GE",
    LocationName: "Georgetown GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "GL",
    PublicStopId: "1GL",
    LocationName: "Guelph Central GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "GO",
    PublicStopId: "1GO",
    LocationName: "Gormley GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "GU",
    PublicStopId: "1GU",
    LocationName: "Guildwood GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "HA",
    PublicStopId: "1HA",
    LocationName: "Hamilton GO Centre",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "KC",
    PublicStopId: "1KC",
    LocationName: "King City GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "KE",
    PublicStopId: "1KE",
    LocationName: "Kennedy GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "KI",
    PublicStopId: "1KI",
    LocationName: "Kitchener GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "KP",
    PublicStopId: "1KP",
    LocationName: "Kipling GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "LA",
    PublicStopId: "1LA",
    LocationName: "Langstaff GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "LI",
    PublicStopId: "1LI",
    LocationName: "Old Elm GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "LO",
    PublicStopId: "1LO",
    LocationName: "Long Branch GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "LS",
    PublicStopId: "1LS",
    LocationName: "Lisgar GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "MA",
    PublicStopId: "1MA",
    LocationName: "Malton GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "ME",
    PublicStopId: "1ME",
    LocationName: "Meadowvale GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "MI",
    PublicStopId: "1MI",
    LocationName: "Mimico GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "MJ",
    PublicStopId: "1MJ",
    LocationName: "Mount Joy GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "MK",
    PublicStopId: "1MK",
    LocationName: "Milliken GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "ML",
    PublicStopId: "1ML",
    LocationName: "Milton GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "MO",
    PublicStopId: "1MO",
    LocationName: "Mount Pleasant GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "MP",
    PublicStopId: "1MP",
    LocationName: "Maple GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "MR",
    PublicStopId: "1MR",
    LocationName: "Markham GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "NE",
    PublicStopId: "1NE",
    LocationName: "Newmarket GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "NI",
    PublicStopId: "1NI",
    LocationName: "Niagara Falls GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "OA",
    PublicStopId: "1OA",
    LocationName: "Oakville GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "OL",
    PublicStopId: "1OL",
    LocationName: "Old Cummer GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "OR",
    PublicStopId: "1OR",
    LocationName: "Oriole GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "OS",
    PublicStopId: "1OS",
    LocationName: "Durham College Oshawa GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "PA",
    PublicStopId: "1PA",
    LocationName: "Pearson Airport Terminal 1",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "PIN",
    PublicStopId: "1PIN",
    LocationName: "Pickering GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "PO",
    PublicStopId: "1PO",
    LocationName: "Port Credit GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "RI",
    PublicStopId: "1RI",
    LocationName: "Richmond Hill GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "RO",
    PublicStopId: "1RO",
    LocationName: "Rouge Hill GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "RU",
    PublicStopId: "1RU",
    LocationName: "Rutherford GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "SC",
    PublicStopId: "1SC",
    LocationName: "Scarborough GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "SCTH",
    PublicStopId: "1SCTH",
    LocationName: "St. Catharines GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "SR",
    PublicStopId: "1SR",
    LocationName: "Streetsville GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "ST",
    PublicStopId: "1ST",
    LocationName: "Stouffville GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "UI",
    PublicStopId: "1UI",
    LocationName: "Unionville GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "UN",
    PublicStopId: "1UN",
    LocationName: "Union Station GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "WE",
    PublicStopId: "1WE",
    LocationName: "Weston GO",
    LocationType: "Train Station",
  },
  {
    LocationCode: "WH",
    PublicStopId: "1WH",
    LocationName: "Whitby GO",
    LocationType: "Train & Bus Station",
  },
  {
    LocationCode: "WR",
    PublicStopId: "1WR",
    LocationName: "West Harbour GO",
    LocationType: "Train & Bus Station",
  },
];

const TRAIN_STATIONS: { [k: string]: string } = {
  AC: "Acton GO",
  AD: "Allandale Waterfront GO",
  AG: "Agincourt GO",
  AJ: "Ajax GO",
  AL: "Aldershot GO",
  AP: "Appleby GO",
  AU: "Aurora GO",
  BA: "Barrie South GO",
  BD: "Bradford GO",
  BE: "Bramalea GO",
  BL: "Bloor GO",
  BM: "Bloomington GO",
  BO: "Bronte GO",
  BR: "Brampton Innovation District GO",
  BU: "Burlington GO",
  CE: "Centennial GO",
  CL: "Clarkson GO",
  CO: "Cooksville GO",
  DA: "Danforth GO",
  DI: "Dixie GO",
  DW: "Downsview Park GO",
  EA: "East Gwillimbury GO",
  EG: "Eglinton GO",
  ER: "Erindale GO",
  ET: "Etobicoke North GO",
  EX: "Exhibition GO",
  GE: "Georgetown GO",
  GL: "Guelph Central GO",
  GO: "Gormley GO",
  GU: "Guildwood GO",
  HA: "Hamilton GO Centre",
  KC: "King City GO",
  KE: "Kennedy GO",
  KI: "Kitchener GO",
  KP: "Kipling GO",
  LA: "Langstaff GO",
  LI: "Old Elm GO",
  LO: "Long Branch GO",
  LS: "Lisgar GO",
  MA: "Malton GO",
  ME: "Meadowvale GO",
  MI: "Mimico GO",
  MJ: "Mount Joy GO",
  MK: "Milliken GO",
  ML: "Milton GO",
  MO: "Mount Pleasant GO",
  MP: "Maple GO",
  MR: "Markham GO",
  NE: "Newmarket GO",
  NI: "Niagara Falls GO",
  OA: "Oakville GO",
  OL: "Old Cummer GO",
  OR: "Oriole GO",
  OS: "Durham College Oshawa GO",
  PA: "Pearson Airport Terminal 1",
  PIN: "Pickering GO",
  PO: "Port Credit GO",
  RI: "Richmond Hill GO",
  RO: "Rouge Hill GO",
  RU: "Rutherford GO",
  SC: "Scarborough GO",
  SCTH: "St. Catharines GO",
  SR: "Streetsville GO",
  ST: "Stouffville GO",
  UI: "Unionville GO",
  UN: "Union Station GO",
  WE: "Weston GO",
  WH: "Whitby GO",
  WR: "West Harbour GO",
};

const LINES: { [k: string]: string } = {
  BR: "Barrie",
  GT: "Kitchener",
  LE: "Lakeshore East",
  LW: "Lakeshore West",
  MI: "Milton",
  RH: "Richmond Hill",
  ST: "Stouffville",
};

const CURRENT_STATUS: { [k: string]: string } = {
  INCOMING_AT: "Approaching",
  STOPPED_AT: "Stopped at",
  IN_TRANSIT_TO: "Heading towards",
};

export { CURRENT_STATUS, LINES, TRAIN_STATIONS, TRAIN_STATIONS_DATA };
